<?php
require_once 'config.php';
define('TITLE', 'Sizzle - Terms of Service');
require __DIR__.'/header.php';
?>
</head>
<body id="terms">

<!-- =========================
     HEADER
============================== -->
<header class="header" data-stellar-background-ratio="0.5" id="account-profile">

<!-- SOLID COLOR BG -->
<div class=""> <!-- To make header full screen. Use .full-screen class with solid-color. Example: <div class="solid-color full-screen">  -->
    <?php require __DIR__.'/navbar.php';?>
</div>
<!-- /END COLOR OVERLAY -->
</header>
	<div>
		<summary id="terms-content">
			<h1 id="terms-header">
			    	Terms of Service
			</h1>
			<p>
			    <em>Last Updated: November 11, 2014</em>
			</p>
			<h2>
			    	Acceptance of the Terms of Service
			</h2>
			<p>
			    Welcome to the website of Giftly, Inc. (<strong>"Giftly"</strong>, <strong>"we"</strong> or <strong>"us"</strong>). The following terms and conditions (these <strong>"Terms of Service"</strong>), govern your access to and use of this web site or application, including any software (including, without limitation, software, code, files, images, or fonts contained in or generated by the software, accompanying data, and other embedded software), and any accompanying documentation (collectively, the "    <strong>Platform</strong>").
			</p>
			<p>
			Please read the Terms of Service carefully before you start to use the Platform. <strong>By using the Platform you accept and agree to be bound and abide by these Terms of Service and our Privacy Policy, found at </strong> https://www.gosizzle.io/privacypolicy <strong>incorporated herein by reference.</strong> If you do not want to agree to these Terms of Service, you must not access or use the Platform.
			</p>
			<p>
			    This Platform is offered and available to users who are 13 years of age or older. By using this Platform, you represent and warrant that you meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Platform.
			</p>
			<h2>
			    Changes to the Terms of Service
			</h2>
			<p>
			    We may revise and update these Terms of Service from time to time in our sole discretion. All changes are effective immediately when we post them, and
			    apply to all access to and use of the Platform thereafter.
			</p>
			<p>
			    Your continued use of the Platform following the posting of revised Terms of Service means that you accept and agree to the changes. You are expected to
			    check this page from time to time so you are aware of any changes, as they are binding on you.
			</p>
			<h2>
			    Accessing the Platform and Account Security
			</h2>
			<p>
			    We reserve the right to withdraw or amend this Platform, and any service or material we provide on the Platform, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Platform is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Platform, or the entire Platform, to users, including registered users.
			</p>
			<p>
			    You are responsible for:
			</p>
			<p>
			    · Making all arrangements necessary for you to have access to the Platform.
			</p>
			<p>
			    · Ensuring that all persons who access the Platform through your internet connection are aware of these Terms of Service and comply with them.
			</p>
			<p>
			    To access the Platform or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition
			    of your use of the Platform that all the information you provide on the Platform is correct, current and complete. You agree that all information you
			    provide to register with this Platform or otherwise, including but not limited to through the use of any interactive features on the Platform, is governed
			    by our <em>Privacy Policy</em> https://www.gosizzle.io/privacypolicy and you consent to all actions we take with respect to your information consistent
			    with our Privacy Policy.
			</p>
			<p>
			    If you choose, or are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such
			    information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and
			    agree not to provide any other person with access to this Platform or portions of it using your user name, password or other security information. You
			    agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure
			    that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer
			    so that others are not able to view or record your password or other personal information.
			</p>
			<p>
			    We have the right to disable any user name, password or other identifier, whether chosen by you or provided by us, at any time if, in our opinion, you have
			    violated any provision of these Terms of Service.
			</p>
			<h2>
			    Intellectual Property Rights
			</h2>
			<p>
			    The Platform and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and
			    audio, and the design, selection and arrangement thereof), are owned by Giftly, its licensors or other providers of such material and are protected by
			    United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.
			</p>
			<p>
			    These Terms of Service permit you to use the Platform for your personal, non-commercial use only. You must not reproduce, distribute, modify, create
			    derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on our Platform. You must not:
			</p>
			<p>
			    · Modify copies of any materials from this site.

			</p>
			<p>
			    · Delete or alter any copyright, trademark or other proprietary rights notices from copies of materials from this site.
			</p>
			<p>
			    If you print, copy, modify or otherwise use or provide any other person with access to any part of the Platform in breach of the Terms of Service, your
			    right to use the Platform will cease immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title
			    or interest in or to the Platform or any content on the Platform is transferred to you, and all rights not expressly granted are reserved by Giftly. Any
			    use of the Platform not expressly permitted by these Terms of Service is a breach of these Terms of Service and may violate copyright, trademark and other
			    laws.
			</p>
			<h2>
			    Trademarks
			</h2>
			<p>
			    Giftly’s name, logo and all related names, logos, product and service names, designs and slogans are trademarks of Giftly or its affiliates or licensors.
			    You must not use such marks without the prior written permission of Giftly. All other names, logos, product and service names, designs and slogans on this
			    Platform are the trademarks of their respective owners.
			</p>
			<h2>
			    Prohibited Uses
			</h2>
			<p>
			    You may use the Platform only for lawful purposes and in accordance with these Terms of Service. You agree not to use the Platform:
			</p>
			<p>
			    · In any way that violates any applicable federal, state, local or international law or regulation (including, without limitation, any laws regarding the
			    export of data or software to and from the US or other countries).
			</p>
			<p>
			    · For the purpose of exploiting, harming or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for
			    personally identifiable information or otherwise.
			</p>
			<p>
			    · To send, knowingly receive, upload, download, use or re-use any material which does not comply with the Content Standards set out in these Terms of
			    Service.
			</p>
			<p>
			    · To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail", "chain letter" or "spam" or any other similar
			    solicitation.
			</p>
			<p>
			    · To impersonate or attempt to impersonate Giftly, a Giftly employee, another user or any other person or entity (including, without limitation, by using
			    e-mail addresses or screen names associated with any of the foregoing).
			</p>
			<p>
			    · To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Platform, or which, as determined by us, may harm Giftly or
			    users of the Platform or expose them to liability.
			</p>
			<p>
			    Additionally, you agree not to:
			</p>
			<p>
			    · Use the Platform in any manner that could disable, overburden, damage, or impair the site or interfere with any other party's use of the Platform,
			    including their ability to engage in real time activities through the Platform.
			</p>
			<p>
			    · Use any robot, spider or other automatic device, process or means to access the Platform for any purpose, including monitoring or copying any of the
			    material on the Platform.
			</p>
			<p>
			    · Use any manual process to monitor or copy any of the material on the Platform or for any other unauthorized purpose without our prior written consent.
			</p>
			<p>
			    · Use any device, software or routine that interferes with the proper working of the Platform.
			</p>
			<p>
			    · Introduce any viruses, trojan horses, worms, logic bombs or other material which is malicious or technologically harmful.
			</p>
			<p>
			    · Attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Platform, the server on which the Platform is stored, or any
			    server, computer or database connected to the Platform.
			</p>
			<p>
			    · Otherwise attempt to interfere with the proper working of the Platform.
			</p>
			<h2>
			    User Contributions
			</h2>
			<p>
			    The Platform contains other interactive features (collectively, <strong>"Interactive Services"</strong>) that allow users to post, submit, publish, display or transmit to
			    other users or other persons content or materials (collectively, <strong>"User Contributions"</strong>) on or through the Platform.
			</p>
			<p>
			    All User Contributions must comply with the Content Standards set out in these Terms of Service. By providing any User Contribution on the Platform, you
			    grant us and our licensees, successors and assigns the right to use, reproduce, modify, perform, display, distribute and otherwise disclose to third
			    parties any such material according to your account settings.
			</p>
			<p>
			    You represent and warrant that:
			</p>
			<p>
			    · You own or control all rights in and to the User Contributions and have the right to grant the license granted above to us and our licensees, successors
			    and assigns.
			</p>
			<p>
			    · All of your User Contributions do and will comply with these Terms of Service.
			</p>
			<p>
			    You understand and acknowledge that you are responsible for any User Contributions you submit or contribute, and you, not Giftly, have fully responsibility
			    for such content, including its legality, reliability, accuracy and appropriateness.
			</p>
			<p>
			    We are not responsible, or liable to any third party, for the content or accuracy of any User Contributions posted by you or any other user of the
			    Platform.
			</p>
			<h2>
			    Monitoring and Enforcement; Termination
			</h2>
			<p>
			    We have the right to:
			</p>
			<p>
			    · Remove or refuse to post any User Contributions for any or no reason in our sole discretion.
			</p>
			<p>
			    · Take any action with respect to any User Contribution that we deem necessary or appropriate in our sole discretion, including if we believe that such
			    User Contribution violates the Terms of Service, including the Content Standards, infringes any intellectual property right or other right of any person or
			    entity, threatens the personal safety of users of the Platform or the public or could create liability for Giftly.
			</p>
			<p>
			    · Disclose your identity or other information about you to any third party who claims that material posted by you violates their rights, including their
			    intellectual property rights or their right to privacy.
			</p>
			<p>
			    · Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Platform.
			</p>
			<p>
			    · Terminate or suspend your access to all or part of the Platform for any violation of these Terms of Service.
			</p>
			<p>
			    Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to
			    disclose the identity or other information of anyone posting any materials on or through the Platform. YOU WAIVE AND HOLD HARMLESS GIFTLY FROM ANY CLAIMS
			    RESULTING FROM ANY ACTION TAKEN BY GIFTLY DURING OR AS A RESULT OF ITS INVESTIGATIONS AND FROM ANY ACTIONS TAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY
			    EITHER GIFTLY OR LAW ENFORCEMENT AUTHORITIES.
			</p>
			<p>
			    However, we cannot review all material before it is posted on the Platform, and cannot ensure prompt removal of objectionable material after it has been
			    posted. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications or content provided by any user or third
			    party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section.
			</p>
			<h2>
			    Content Standards
			</h2>
			<p>
			    These content standards apply to any and all User Contributions and use of Interactive Services. User Contributions must in their entirety comply with all
			    applicable federal, state, local and international laws and regulations. Without limiting the foregoing, User Contributions must not:
			</p>
			<p>
			    · Contain any material which is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory or otherwise objectionable.
			</p>
			<p>
			    · Promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation
			    or age.
			</p>
			<p>
			    · Infringe any patent, trademark, trade secret, copyright or other intellectual property or other rights of any other person.
			</p>
			<p>
			    · Violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal
			    liability under applicable laws or regulations or that otherwise may be in conflict with these Terms of Service and our Privacy Policy
			    https://www.gosizzle.io/privacypolicy
			</p>
			<p>
			    · Be likely to deceive any person.
			</p>
			<p>
			    · Promote any illegal activity, or advocate, promote or assist any unlawful act.
			</p>
			<p>
			    · Cause annoyance, inconvenience or needless anxiety or be likely to upset, embarrass, alarm or annoy any other person.
			</p>
			<p>
			    · Impersonate any person, or misrepresent your identity or affiliation with any person or organization.
			</p>
			<p>
			    · Involve commercial activities or sales, such as contests, sweepstakes and other sales promotions, barter or advertising.
			</p>
			<p>
			    · Give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case.
			</p>
			<h2>
			    Copyright Infringement
			</h2>
			<p>
			    If you believe that content you own has been copied and made accessible in a manner that violates your intellectual property rights, please notify us
			    immediately. You may submit a notification pursuant to the Digital Millennium Copyright Act (see 17 U.S.C § 512(c)(3)) to our copyright agent at
			    gpeters@gosizzle.io.
			</p>
			<h2>
			    Reliance on Information Posted
			</h2>
			<p>
			    The information presented on or through the Platform is made available solely for general information purposes. We do not warrant the accuracy,
			    completeness or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and
			    responsibility arising from any reliance placed on such materials by you or any other visitor to the Platform, or by anyone who may be informed of any of
			    its contents.
			</p>
			<p>
			    This Platform content provided by third parties, including materials provided by other users, bloggers and third-party licensors, syndicators, aggregators
			    or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other
			    than the content provided by Giftly, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do
			    not necessarily reflect the opinion of Giftly. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials
			    provided by any third parties.
			</p>
			<h2>
			    Information About You and Your Visits to the Platform
			</h2>
			<p>
			All information we collect on this Platform is subject to our Privacy Policy    <a href="https://www.gosizzle.io/privacy">https://www.gosizzle.io/privacypolicy</a>. By using the Platform, you consent to all actions taken by
			    us with respect to your information in compliance with the Privacy Policy.
			</p>
			<h2>
			    Links from the Platform
			</h2>
			<p>
			    If the Platform contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes
			    links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources,
			    and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third party
			    websites linked to this Platform, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.
			</p>
			<h2>
			    Geographic Restrictions
			</h2>
			<p>
			    The owner of the Platform is based in the state of Tennessee in the United States. We provide this Platform for use only by persons located in the United
			    States. We make no claims that the Platform or any of its content is accessible or appropriate outside of the United States. Access to the Platform may not
			    be legal by certain persons or in certain countries. If you access the Platform from outside the United States, you do so on your own initiative and are
			    responsible for compliance with local laws.
			</p>
			<h2>
			    Disclaimer of Warranties
			</h2>
			<p>
			    You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Platform will be free of
			    viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for
			    anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. WE
			    WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE DUE TO YOUR USE OF THE WEBSITE OR ANY SERVICES OBTAINED THROUGH THE WEBSITE OR ON ANY WEBSITE LINKED TO IT.
			</p>
			<p>
			    YOUR USE OF THE WEBSITE, ITS CONTENT AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE WEBSITE, ITS CONTENT AND ANY SERVICES
			    OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
			    NEITHER GIFTLY NOR ANY PERSON ASSOCIATED WITH GIFTLY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY,
			    ACCURACY OR AVAILABILITY OF THE WEBSITE. WITHOUT LIMITING THE FOREGOING, NEITHER GIFTLY NOR ANYONE ASSOCIATED WITH GIFTLY REPRESENTS OR WARRANTS THAT THE
			    WEBSITE, ITS CONTENT OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE WILL BE ACCURATE, RELIABLE, ERROR-FREE OR UNINTERRUPTED, THAT DEFECTS WILL BE
			    CORRECTED, THAT OUR SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE WEBSITE OR ANY SERVICES, DATA OR
			    MATERIALS OBTAINED THROUGH THE WEBSITE WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.
			</p>
			<p>
			    GIFTLY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
			    MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR PARTICULAR PURPOSE.
			</p>
			<p>
			    THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.
			</p>
			<h2>
			    Limitation on Liability
			</h2>
			<p>
			    IN NO EVENT WILL GIFTLY, ITS AFFILIATES OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS OR DIRECTORS (THE "GIFTLY ENTITIES") BE LIABLE
			    FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE WEBSITE, ANY WEBSITES LINKED TO
			    IT, ANY CONTENT ON THE WEBSITE OR SUCH OTHER WEBSITES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE OR SUCH OTHER WEBSITES, INCLUDING ANY INDIRECT,
			    SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF
			    REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING
			    NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE.
			</p>
			<p>
			    IN NO EVENT WILL THE GIFTLY ENTITIES’ AGGREGATE LIABILITY EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS (U.S. $100.00) OR THE AMOUNT YOU PAID GIFTLY IN
			    THE LAST SIX MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM.
			</p>
			<h2>
			    Indemnification
			</h2>
			<p>
			    You agree to defend, indemnify and hold harmless Giftly, its affiliates, licensors and service providers, and its and their respective officers, directors,
			    employees, contractors, agents, licensors, suppliers, successors and assigns from and against any claims, liabilities, damages, judgments, awards, losses,
			    costs, expenses or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms of Service or your use of the
			    Platform, including, but not limited to, your User Contributions, any use of the Platform's content, services and products other than as expressly
			    authorized in these Terms of Service or your use of any information obtained from the Platform.
			</p>
			<h2>
			    Governing Law and Jurisdiction
			</h2>
			<p>
			    All matters relating to the Platform and these Terms of Service and any dispute or claim arising therefrom or related thereto (in each case, including
			    non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of Tennessee without giving
			    effect to any choice or conflict of law provision or rule (whether of the State of Tennessee or any other jurisdiction).
			</p>
			<p>
			    Any legal suit, action or proceeding arising out of, or related to, these Terms of Service or the Platform shall be instituted exclusively in the federal
			    courts of the United States or the courts of the State of Tennessee in each case located in the City of Nashville and County of Davidson. You waive any and
			    all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.
			</p>
			<h2>
			    Dispute Resolution
			</h2>
			<p>
			    EACH OF THE PARTIES HEREBY KNOWINGLY, VOLUNTARILY AND INTENTIONALLY WAIVES ANY RIGHT IT MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY LITIGATION ARISING
			    OUT OF, RELATING TO OR IN CONNECTION WITH THESE TERMS. FURTHER, EACH PARTY CERTIFIES THAT NO REPRESENTATIVE OR AGENT OF EITHER PARTY HAS REPRESENTED,
			    EXPRESSLY OR OTHERWISE, THAT SUCH PARTY WOULD NOT, IN THE EVENT OF SUCH LITIGATION, SEEK TO ENFORCE THIS WAIVER OF RIGHT TO JURY TRIAL PROVISION. Each of
			    the parties acknowledges that this Section is a material inducement for the other party to enter into this agreement. You acknowledge and agree that,
			    regardless of any statute or law to the contrary, any claim or cause of action you may have arising out of, relating to, or in connection with this
			    agreement must be filed within one calendar year after such claim or cause of action arises, or forever be barred.
			</p>
			<h2>
			    Limitation on Time to File Claims
			</h2>
			<p>
			    ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE OR THE WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER
			    THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.
			</p>
			<h2>
			    Waiver and Severability
			</h2>
			<p>
			    No waiver by Giftly of any term or condition set forth in these Terms of Service shall be deemed a further or continuing waiver of such term or condition
			    or a waiver of any other term or condition, and any failure of Giftly to assert a right or provision under these Terms of Service shall not constitute a
			    waiver of such right or provision.
			</p>
			<p>
			    If any provision of these Terms of Service is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any
			    reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Service will continue in
			    full force and effect.
			</p>
			<h2>
			    Entire Agreement
			</h2>
			<p>
			    The Terms of Service and our Privacy Policy constitute the sole and entire agreement between you and Giftly with respect to the Platform and supersede all
			    prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Platform.
			</p>
		</summary>
	</div>

    <?php require __DIR__.'/footer.php';?>
</body>
</html>
